"use client";

import type { Metadata } from "next";
import { ScoreProvider } from "./context/ScoreContext";

import { Inter } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "MEGA Carcassone",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased h-screen bg-stone-200`}>
        <ScoreProvider>{children}</ScoreProvider>
      </body>
    </html>
  );
}
